#ifndef MY_LICCSU_INCLUDES
#define MY_LICCSU_INCLUDES

#include "imgui.h"
#include "imgui_impl_android.h"
#include "imgui_impl_opengl3.h"
#include "imgui_internal.h"
#include "font.h"
#include "CN.h"
#include "图标字体.h"
#include "图标.h"
#include <string>
#include <android/log.h>
#include <android/asset_manager.h>
#include <EGL/egl.h>
#include <GLES3/gl3.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <unistd.h>
#include <android/log.h>
#include <pthread.h>
#include <unistd.h>
#include <imgui_internal.h>
#include <sys/sysinfo.h>
#include <jni.h>
#include <android/native_window.h>
#include <android/native_window_jni.h>
#include <pthread.h>
#include <unistd.h>
#include <android/log.h>
#include <android/asset_manager_jni.h>
#include <sys/time.h>
#include <dirent.h>
#include <sys/ptrace.h>
#include <sys/uio.h>
#include <sys/syscall.h>
#include <unistd.h>
#include <math.h>
#include "stb_image.h"
#include <GLES3/gl3.h>
#include <linux/input.h>
#include <linux/uinput.h>

#endif
